FROM python:3.12.1-slim-bookworm

# 1) Put everything under /app
WORKDIR /app

# 2) Install Python deps
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 3) Copy source code into the image
COPY app/ /app/app/

# 4) Expose FastAPI port
EXPOSE 8000

# 5) Start the API using Uvicorn

CMD ["uvicorn", "app.Api_v1:app", "--host", "0.0.0.0", "--port", "8000"]
